http: # http server config
  listen: 127.0.0.1:3000 # listen address
database: # database
  dialect: mysql # database dialect
  host: localhost # database host
  port: 3306 # database port
  user: root # database user
  password: root # database password
  database: sms # database name
  debug: true
  timezone: UTC
fcm:
  credentials_json: >
    {
    ...
    }
  timeout_seconds: 1
  debounce_seconds: 1
tasks:
  hashing:
    interval_seconds: 15
